version: "3"
services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
      args:
        UPLOAD_FOLDER : /upload_files
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - redis
  worker:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    depends_on:
      - redis
  monitor:
    build:
      context: celery-queue
      dockerfile: Dockerfile
      args:
        UPLOAD_FOLDER : /upload_files
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    build:
      context: redis
      dockerfile: Dockerfile